version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ianorth-backend
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/ianorth_sucata_v2.db:/app/ianorth_sucata_v2.db
      - ./backend/src/static:/app/src/static

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: "http://172.19.96.1:8000"
    container_name: ianorth-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
